amk/urls.py
from django.urls import path #
from . import views   #


#-------------------------------------------------------------
app_name='amk'
urlpatterns = [
    path('', views.index, name='index'),  #    /amk/  , veiw.index 실행  ,  url alias index
    path('about', views.about, name='about'),  #/amk/intro/ , view.intro , url alias index     이면  디테일호출
    path('contact', views.contact, name='contact'),
    path('post', views.post, name='post'),
    path('storege', views.storege, name='storege'),
    path('storege_detail',views.storege_detail, name='storege_detail'),
#    path('<int:question_id>/results/', views.results, name='results'),        #/amk/5/results   이면  veiws.results 호출
#    path('<int:question_id>/vote/', views.vote, name='vote'),#/amk/5/vote   이면  veiws.vote 호출
  ]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('amk/',include('amk.urls')),
    path('',RedirectView.as_view(url="/amk/", permanent=True)),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amk/models.py
import datetime                #

from django.db import models
from django.utils import timezone #
from django.contrib import admin
from django.urls import reverse

# Create your models here.
#데이터베이스
#-----------------------------------------------------------------------------
class Category(models.Model):
  name = models.CharField(max_length=50, help_text="블로그 글의 분류를 입력하세요.(ex:일상)")

  def __str__(self):            #자기를 어떻게 표시할 것인가
    return self.name            #name으로 표시하겟다

class Post(models.Model):
  tittle = models.CharField(max_length=200)
  title_image = models.ImageField(blank=True)   # pip install Pillow   이미지필드를 사용하기위해서
  content = models.TextField()
  createDate = models.DateTimeField(auto_now_add=True)
  updateDate = models.DateTimeField(auto_now_add=True)
  #하나의 글을 여러가지의 분류에 해당될수 있다
  category = models.ManyToManyField(Category, help_text="글의 분류를 설정하세요.")

  def __str__(self):
    return self.tittle

  #1번글의 경우 -> single/1
  def get_absolute_url(self):     # 자기자신을 찾아올수있는 주소를 어떻게
    return  reverse("single", args=[str(self.id)])             #single 은 html url 이름

  def is_content_more300(self):
    return len(self.content) > 300

  def get_content_under300(self):
    return self.content[:300]

  #python manage.py makemigrations
  #python manage.py migrate
  #python manage.py createsuperuser

amk/views.py
from django.shortcuts import render , get_object_or_404  , redirect     #
from django.http import HttpResponse , HttpResponseRedirect   #
from .models import Category, Post                          #
from django.urls import reverse                               #
from django.views import generic                              #
from django.template import loader                            #
from django.utils import timezone                             #
from django.http import Http404
# Create your views here.


def index(request):

    context= {

             }
    return render(request, "amk/index.html",context=context)


def contact(request):

    context= {

             }
    return render(request, "amk/contact.html",context=context)


def about(request):

    context= {

             }
    return render(request, "amk/about.html",context=context)


def post(request):

    context= {

             }
    return render(request, "amk/post.html",context=context)


def storege(request):
    st_msg = Post.objects.order_by('updateDate')[::-1][:6]

    context= {
              'st_msg': st_msg,
             }
    return render(request, "amk/storege.html",context=context)



def storege_detail(request):

    if request.method == 'POST':

        Post.objects.create(tittle=request.POST['tittle'], content=request.POST['content'])            #포스트생성

        return HttpResponseRedirect('storege')

amk/templates/amk/about.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> amk의블로그 - 맹블 </title>
        <link rel="icon" type="image/x-icon" href="{% static 'amk/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'amk/CSS/styles.css' %}">
    </head>

  <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="<% url 'amk:index' %>">안녕~?</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                       <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:about' %}">About me</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:post' %}">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:contact' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:storege' %}">Storege</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'amk/assets/img/about-mk.jpg' %})" >
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I did.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p></p>
                        <a href="#!"><img class="img-fluid" src={% static 'amk/assets/img/detail-sam.jpg' %} alt="..." /></a>
                        <p align="center" style="font-size:24px; font-family:'돋보움'";>변압기 및 리액터 설계 </p>
                        <br>
                        <br>
                        <a href="#!"><img class="img-fluid" src={% static 'amk/assets/img/detail-lucent.jpg' %} alt="..." /></a>
                        <p align="center" style="font-size:24px; font-family:'돋보움'";>킥보드 및 주변장치 개발</p>
                        <br>
                        <br>
                        <a href="#!"><img class="img-fluid" src={% static 'amk/assets/img/detail-plus.jpg' %} alt="..." /></a>
                        <p align="center" style="font-size:24px; font-family:'돋보움'";>시설관리</p>

                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; 맹기의 블로그 2021</div>
                    </div>
                </div>
            </div>
         </footer>

          <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'amk/js/scripts.js' %}"></script>
  </body>
</html>

amk/templates/amk/index.html
<!DOCTYPE html>
{% load static %}


<html lang="en">

    <head>
     {% csrf_token %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> amk의블로그 - 맹블 </title>
        <link rel="icon" type="image/x-icon" href="{% static 'amk/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'amk/CSS/styles.css' %}">
    </head>

 <body>
     <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand"  href=#>안녕~?</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:about' %}">About me</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:post' %}">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:contact' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:storege' %}">Storege</a></li>
                    </ul>
                </div>
            </div>
        </nav>


      <header class="masthead" style="background-image: url({% static 'amk/assets/img/home-bg.jpg' %})" >
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>파이썬-장고, Bootstrap 으로 만들었어요 그밖에 AWS(S3,EC2,DB-MYSQL),nginx </h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

<!----------------------------- Main Content--------------------------------->
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
       <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'amk:post' %}">
                            <h2 class="post-title">여긴 취미로할가 </h2>
                            <h3 class="post-subtitle">등산을 다니는거 같은</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 24, 2021
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'amk:storege' %}"><h2 class="post-title">글을남겨줘 ㅋ</h2></a>
                        <h3 class="post-subtitle">글이 DB에 저장됨</h3>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on September 18, 2021
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'amk:about' %}">
                            <h2 class="post-title">나에대해서 간단히 소개를 하자면</h2>
                            <h3 class="post-subtitle">대책없이 사는 생각없는 주정뱅이랄가</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on August 24, 2021
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="https://github.com/Anmyungnki">
                            <h2 class="post-title">git 주소는</h2>
                            <h3 class="post-subtitle">https://github.com/Anmyungnki</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                            on July 8, 2021
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
       </div>
      </div>
    </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Copyright &copy; 맹기의 블로그 2021</div>
                    </div>
                </div>
            </div>
        </footer>

<!----------------------------- Main Content  END--------------------------------->




 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
 <script src="{% static 'amk/js/scripts.js' %}"></script>

 </body>
</html>

amk/templates/amk/storege.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>amk의블로그 - 맹블</title>
        <link rel="icon" type="image/x-icon" href="{% static 'amk/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'amk/CSS/styles.css' %}">
    </head>

  <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="<% url 'amk:index' %>">안녕~?</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                       <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:about' %}">About me</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:post' %}">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:contact' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'amk:storege' %}">Storege</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'amk/assets/img/detail-bg.jpg' %})" >
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>테스트 중</h1>
                            <span class="subheading">db에 저장하면서 동작중</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p><strong>아래내용은 DB에 저장된 값들</strong></p>

                        <form id="dblist" action="{% url 'amk:storege' %}" method="post">
                        {% csrf_token %}
                            {% for stri in st_msg %}
                            <li style="height: 1rem"><strong>name:</strong> {{stri.tittle}} </li>
                            <p style="height: 1rem; font-size:1rem; font-family:굴림체" > &nbsp;&nbsp;&nbsp;&nbsp; {{stri.content}}  </p>
                            <br>
                            {% endfor %}
                        </form>
                        <br>

                        <form id="contactForm"  action="{% url 'amk:storege_detail' %}" method="post" >
                         {% csrf_token %}
                          <div class="form-floating">
                             <input class="form-control" id='inputid' type='text' name="tittle" placeholder="Enter your name..." data-sb-validations="required" />
                             <label for="inputid">Name</label>
                             <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                          </div>
                                 <br>
                          <div class="form-floating">
                             <input class="form-control" name="content" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required" />
                             <label for="message">Message</label>
                             <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                          </div>
                                 <br>
                            <input class="form-control" type="submit" style="font-size: 1.5rem;" value="Input">
                        </form>
                        <br>

                    </div>
                </div>
            </div>
        </main>

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; 맹기의 블로그 2021</div>
                    </div>
                </div>
            </div>
         </footer>

          <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'amk/js/scripts.js' %}"></script>
  </body>
</html>